add contact checker
dekalee/mailjet-bundle pull request #6
Opened 2017-02-27 10:28 UTC by Nandotk

2017-02-27 10:52 UTC, nicolasThal reviewed
I think you forgot to commit the tests :)

2017-02-28 10:44 UTC, sempixel approved these changes

2017-02-28 12:59 UTC, nicolasThal requested changes

2017-02-28 12:59 UTC, nicolasThal commented on spec/Dekalee/MailjetBundle/Checker/ContactCheckerSpec.php
> +    )
psr : `)` and `{` should be on the same line separated by a ` ` : `) {`

2017-02-28 12:59 UTC, nicolasThal commented on spec/Dekalee/MailjetBundle/Checker/ContactCheckerSpec.php
> +    )
psr : `)` and `{` should be on the same line separated by a ` ` : `) {`

2017-02-28 12:59 UTC, nicolasThal commented on spec/Dekalee/MailjetBundle/Checker/ContactCheckerSpec.php
> +    )
psr : `)` and `{` should be on the same line separated by a ` ` : `) {`

2017-02-28 13:11 UTC, yoye commented on MailjetBundle/Checker/ContactChecker.php
> +     * hasNoBlockedEmail
On dirait que les commentaires sont auto-générés, du coup ils n'apportent pas grand chose.

2017-02-28 13:11 UTC, yoye commented on MailjetBundle/Checker/ContactChecker.php
> +        } else {
Else inutile car il y a un return dans l'instruction précédente

2017-02-28 13:11 UTC, yoye commented on MailjetBundle/Checker/ContactChecker.php
> +            return 'error';
Ici, on retourne un string et toutes les autres valeurs de retour sont des boolean

2017-02-28 13:23 UTC, Nandotk commented on MailjetBundle/Checker/ContactChecker.php
> +     * hasNoBlockedEmail
ok I delete it

2017-02-28 13:29 UTC, Nandotk commented on MailjetBundle/Checker/ContactChecker.php
> +            return 'error';
I need third return vales, for api error ?

2017-02-28 14:09 UTC, merged